// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ZKvTbfNaf1z-_gFpCEb4djEyqbgoEWc',
    appId: '1:771044559159:web:8f549512ea6373fa43f2b2',
    messagingSenderId: '771044559159',
    projectId: 'dbapplocationetudiant',
    authDomain: 'dbapplocationetudiant.firebaseapp.com',
    storageBucket: 'dbapplocationetudiant.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Fgz4qY9DFq_MwzhO4hvKWguOVg_pRlo',
    appId: '1:771044559159:android:88af10d0f25685ac43f2b2',
    messagingSenderId: '771044559159',
    projectId: 'dbapplocationetudiant',
    storageBucket: 'dbapplocationetudiant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OmiuwnNUmnRr1H0s0vf5HYRXDQOIvfY',
    appId: '1:771044559159:ios:38500eca6203b8ba43f2b2',
    messagingSenderId: '771044559159',
    projectId: 'dbapplocationetudiant',
    storageBucket: 'dbapplocationetudiant.appspot.com',
    iosBundleId: 'com.example.locationPourEtudiants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4OmiuwnNUmnRr1H0s0vf5HYRXDQOIvfY',
    appId: '1:771044559159:ios:9e87d6ff541b655d43f2b2',
    messagingSenderId: '771044559159',
    projectId: 'dbapplocationetudiant',
    storageBucket: 'dbapplocationetudiant.appspot.com',
    iosBundleId: 'com.example.locationPourEtudiants.RunnerTests',
  );
}
